# Site settings
title: Mine DS
email: matthew3311999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mine DS is a modern 2D adaptation of Minecraft for the DS. Features include both survival and multiplayer, saving, water, and more. It has been in active development for years.
# baseurl: "/Website-Examples" # the subpath of your site, e.g. /blog/
url: "http://mineds.t15.org/" # the base hostname & protocol for your site
github_username:  wolfgange3311999

include:
  - .nojekyll

exclude:
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # All files in project
    values:
      show_in_header: false
