/* _____________________________________________
  | 						|
  |		     BlockID.h			|
  |     Part of Mine DS , by CoolAs and Ray	|
  |		Thanks to Dirbaio!		|
  |_____________________________________________|
*/
#define AIR 0
#define STONE 1
#define DIRT 2
#define GRASS 3
#define TORCH 4
#define PUMPKIN_LIGHT 5
#define GLOWSTONE 6
#define LOG 7
#define OAK_WOOD 8
#define OAK_LOG 8
#define BIRCH_WOOD 9
#define PLANK 10
#define PLANKS 10
#define LEAF 11
#define REDWOOD_LEAF 12
#define JUNGLE_LEAF 13
#define GLASS 14
#define CACTUS 15
#define SAND 16
#define BEDROCK 17
#define SNOW_TOP 18
#define SNOW 18
#define SNOW_GRASS 19
#define COAL_ORE 20
#define IRON_ORE 21
#define GOLD_ORE 22
#define DIAMOND_ORE 23
#define REDSTON_ORE 24
#define TNT 25
#define SANDSTONE 26
#define RED_FLOWER 27
#define YELLOW_FLOWER 28
#define IRON_BLOCK 29
#define GOLD_BLOCK 30
#define DIAMOND_BLOCK 31
#define BLACK_WOOL 32
#define RED_WOOL 33
#define DARK_GREEN_WOOL 34
#define BROWN_WOOL 35
#define BlUE_WOOL 36
#define PURPLE_WOOL 37
#define CYAN_WOOL 38
#define GRAY_WOOL 39
#define WHITE_WOOL 40
#define DRAK_GRAY_WOOL 41
#define PINK_WOOL 42
#define LIGHT_GREEN_WOOL 43
#define YELLOW_WOOL 44
#define LIGHT_BLUE_WOOL 45
#define FUCHSIA_WOOL 46
#define ORANGE_WOOL 47
#define LADDER 48
#define JUNGLE_WOOD 49
#define JUNGLE_GRASS 50
#define TALL_GRASS 51
#define SHRUB 52
#define PORKCHOP_RAW 53
#define BEEF_RAW 54
#define LEATHER 55
#define PICKAXE_WOOD 56
#define PICKAXE_STONE 57
#define PICKAXE_IRON 58
#define PICKAXE_GOLD 59
#define PICKAXE_DIAMOND 60
#define COAL 61
#define IRON 62
#define GOLD 63
#define DIAMOND 64
#define STICK 65