/* _____________________________________________
  | 						|
  |		     BlockID.h			|
  |     Part of Mine DS , by CoolAs and Ray	|
  |		Thanks to Dirbaio!		|
  |_____________________________________________|
*/

#define AIR 0
#define STONE 1
#define DIRT 2
#define GRASS 3
#define PLANKS 4
#define SLABS 5
#define TOP_SLABS 6
#define BRICK 7
#define TNT 8
#define TNT_TOP 9
#define TNT_BOTTOM 10
#define COBWEB 11
#define FLOWER_RED 12
#define FLOWER_YELLOW 13
#define SAPLING 15
#define COBBLE 16
#define COBBLESTONE 16
#define BEDROCK 17
#define SAND 18
#define GRAVEL 19
#define LOG 20
#define LOG_TOP 21
#define IRON_BLOCK 22
#define GOLD_BLOCK 23
#define DIAMOND_BLOCK 24
#define CHEST_TOP 25
#define CHEST_SIDE 26
#define CHEST 27
#define MUSHROOM_RED 28
#define MUSHROOM_BROWN 29
#define BLANK_LN1 30
#define FIRE_BLANK_1 31
#define GOLD_ORE 32
#define IRON_ORE 33
#define COAL_ORE 34
#define BOOK_SHELVES 35
#define MOSS_STONE 36
#define OBSIDIAN 37
#define GRASS_BIOME_SIDE 38
#define LONG_GRASS 39
#define GRASS_BIOME 40
#define LARGE_CHEST_1 41
#define LARGE_CHEST_2 42
#define CRAFTING_TABLE_TOP 43
#define FURNACE 44
#define FURNACE_SIDE 45
#define DESPENSER 46
#define FIRE_BLANK_2 47
#define SPONGE 48
#define GLASS 49
#define DIAMOND_ORE 50
#define REDSTONE_ORE 51
#define LEAF_BIOME_1 52
#define LEAF 53
#define STONE_BRICK 54
#define DESERT_SHRUB 55
#define LONG_GRASS_2 56
#define LARGE_CHEST_BACK_1 57
#define LARGE_CHEST_BACK_2 58
#define CRAFTING_TABLE 59
#define CRAFTING_TABLE_2 60
#define FURNACE_LIT 61
#define FURNACE_TOP 62
#define SAPLING_TALK 63
#define WOOL_WHITE 64
#define MOB_SPAWNER 65
#define SNOW 66
#define ICE 67
#define SNOW_GRASS 68
#define CACTUS_TOP 69
#define CACTUS 70
#define CACTUAS_BOTTOM 71 //Why is this tile needed? //When do you see a bottom of a cactus..
#define CLAY 72
#define SUGAR_CANE 73
#define MUSIC_BLOCK 74
#define JUKEBOX 75 //Keyboard cow!!!
#define LILLY_PAD 76
#define MOSS_GRASS 77
#define MOSS_GRASS_TOP 78
#define WHITE_SAPLING 79
#define TORCH 80
#define DOOR_TOP 81
#define IRON_DOOR_TOP 82
#define LADDER 83
#define TRAPDOOR 84
#define IRON_BARS 85
#define FARMLAND_WET 86
#define FARMLAND_DRY 87
#define WHEAT_1 88
#define WHEAT_2 89
#define WHEAT_3 90
#define WHEAT_4 91
#define WHEAT_5 92
#define WHEAT_6 93
#define WHEAT_7 94
#define WHEAT_8 95
#define LAPIS_ORE 160
#define DARK_WOOD 116
#define WHITE_WOOD 117
#define SANDSTONE 192
